# Generated by Django 3.1.1 on 2020-12-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_year', models.CharField(max_length=4)),
                ('income_month', models.CharField(max_length=2)),
                ('income', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.branch')),
            ],
        ),
    ]
