# Generated by Django 3.1.1 on 2020-12-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_storeamount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreAmount',
            new_name='StoreIncome',
        ),
    ]
